version: '3.8'

services:
  app:
    image: tiny_tools
    ports:
      - "5000:5000"
    env_file:
      - .env
    
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
  
volumes:
  redis_data: